###Lab 3

Q1. Array Creation and Manipulation:

• Create different types of arrays (1D, 2D, 3D) using various methods (np.array,
np.arange, np.linspace, etc.).

• Perform basic operations on arrays (indexing, slicing, reshaping, concatenation).

• Investigate array attributes like shape, size, dtype, ndim.

• Use methods like reshape, resize, flatten

In [21]:
import numpy as np

# 1D Array using np.array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1d)

# 2D Array using np.arange
arr2d = np.arange(12).reshape(3, 4)
print("2D Array:", arr2d)

# 3D Array using np.linspace
arr3d = np.linspace(0, 1, 27).reshape(3, 3, 3)
print("3D Array:", arr3d)

# Indexing and Slicing
print("Element at index 2:", arr2d[2])
print("Slice of 2D Array:", arr2d[1:3, 2:])

# Reshaping
arr2d_reshaped = arr2d.reshape(6, 2)
print("Reshaped 2D Array:", arr2d_reshaped)

# Concatenation
arr_concat = np.concatenate((arr1d, arr1d))
print("Concatenated Array:", arr_concat)

# Array Attributes
print("Shape:", arr1d.shape)
print("Size:", arr1d.size)
print("Data Type:", arr1d.dtype)
print("Number of Dimensions:", arr1d.ndim)

# Methods
print("Reshaped 2D Array:", arr2d.reshape(2, 6))
arr2d.resize(2, 6)  # Resizing happens in place
print("Resized 2D Array:", arr2d)
print("Flattened Array:", arr2d.flatten())


1D Array: [1 2 3 4 5]
2D Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
3D Array: [[[0.         0.03846154 0.07692308]
  [0.11538462 0.15384615 0.19230769]
  [0.23076923 0.26923077 0.30769231]]

 [[0.34615385 0.38461538 0.42307692]
  [0.46153846 0.5        0.53846154]
  [0.57692308 0.61538462 0.65384615]]

 [[0.69230769 0.73076923 0.76923077]
  [0.80769231 0.84615385 0.88461538]
  [0.92307692 0.96153846 1.        ]]]
Element at index 2: [ 8  9 10 11]
Slice of 2D Array: [[ 6  7]
 [10 11]]
Reshaped 2D Array: [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
Concatenated Array: [1 2 3 4 5 1 2 3 4 5]
Shape: (5,)
Size: 5
Data Type: int64
Number of Dimensions: 1
Reshaped 2D Array: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Resized 2D Array: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


Q2. Data Loading and Preprocessing:

• Load a dataset (e.g., CSV, Excel) using NumPy.

• Clean and preprocess the data (handling missing values, normalization,
standardization).

• Calculate mean, median, standard deviation, variance, and other statistical
measures.

In [22]:
# Import necessary Libraries
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.impute import SimpleImputer

# Load the iris dataset
iris = datasets.load_iris()
data = iris.data

# Convert to NumPy array
data_np = np.array(data)

# 1. Data Cleaning: Handle missing values (if any)
# For this example, we introduce some missing values to demonstrate imputation
data_np[0, 0] = np.nan  # Inject a missing value for demonstration

# Handle missing values using mean imputation
imputer = SimpleImputer(strategy='mean')
data_clean = imputer.fit_transform(data_np)

# 2. Normalization
scaler = MinMaxScaler()
data_normalized = scaler.fit_transform(data_clean)

# 2. Standardization
scaler_std = StandardScaler()
data_standardized = scaler_std.fit_transform(data_clean)

# 3. Calculate statistical measures
mean = np.mean(data_clean, axis=0)
median = np.median(data_clean, axis=0)
std_dev = np.std(data_clean, axis=0)
variance = np.var(data_clean, axis=0)

# Print statistical measures
print("Mean:\n", mean)
print("Median:\n", median)
print("Standard Deviation:\n", std_dev)
print("Variance:\n", variance)


Mean:
 [5.84832215 3.05733333 3.758      1.19933333]
Median:
 [5.8  3.   4.35 1.3 ]
Standard Deviation:
 [0.82305156 0.43441097 1.75940407 0.75969263]
Variance:
 [0.67741387 0.18871289 3.09550267 0.57713289]
